<table align="left" width=100%>
    <tr>
        <td width="10%">
            <img src="in_class.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                  <b> Inclass - Lab <br> (Day 1) </b>
                </font>
            </div>
        </td>
    </tr>
</table>

##  Table of Content

1. **[One Dimensional Array](#1D)**
2. **[Two Dimensional Array](#2D)**
3. **[Stacking](#Stacking)**
4. **[Splitting](#Splitting)**
5. **[For Loop](#For Loop)**

**Import the NumPy library before solving the exercises**

### Let's begin with some hands-on practice exercises

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below: (or create your own list)**<br>

    list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

In [1]:
import pandas as pd
import numpy as np

list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

print('Original List: ',list_temperature)
array1 = np.array(list_temperature)
print('One-dimensional NumPy array: ',array1)

Original List:  [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]
One-dimensional NumPy array:  [3.04 1.65 5.76 1.66 1.54 4.69 2.68]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

    weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [2]:
# method 1:

weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

weight_array = np.array(weights)

weight_array[weight_array > 68]



array([74.2, 85. , 74. , 70.5, 86. , 82. ])

In [3]:
# method 2:


weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

import pandas as pd
import numpy as np

weights_array = np.array(weights)

print('1D array of weights of 10 students: ', weights_array)

m = np.max(weights_array)

weights_array_2 = []

for i in weights_array:
    if 68 < i <= m:
        weights_array_2.append(True)
    else:
        weights_array_2.append(False)
    

new_weights = weights_array[weights_array_2]

print('All the weights greater than 68: ', new_weights)

1D array of weights of 10 students:  [74.2 85.  74.  67.9 52.  70.5 86.  51.8 64.  82. ]
All the weights greater than 68:  [74.2 85.  74.  70.5 86.  82. ]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [4]:
# random.randint() is one of the function for doing random sampling in numpy. 
# It returns an array of specified shape and fills it with random integers from low (inclusive) to high (exclusive), 
# i.e. in the interval(low, high)

import pandas as pd
import numpy as np
n = np.random.randint(low=20, high=41, size=10)
print(n)

[35 20 22 24 36 29 34 39 25 30]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a program to get the fifth power of the first five positive integers
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [5]:
import pandas as pd
import numpy as np

a = np.arange(1,6)
print('First five positive integers:',a)

b= np.power(a,5)
print('Raised to the fifth power:',b)

First five positive integers: [1 2 3 4 5]
Raised to the fifth power: [   1   32  243 1024 3125]


In [6]:
FFPI = [1,2,3,4,5]
import numpy as np
print('First five positive integers:',FFPI)
FFPI_array = np.array(FFPI)
print('Array of the First five positive integers:',FFPI_array)

new_array = np.power(FFPI_array,5)
print('Raised to the fifth power:',new_array)

First five positive integers: [1, 2, 3, 4, 5]
Array of the First five positive integers: [1 2 3 4 5]
Raised to the fifth power: [   1   32  243 1024 3125]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to create an array of all the odd integers from 50 to 100 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [7]:
import numpy as np
array1 =np.arange(51,101,2)
print('Array of all the odd integers from 50 to 100: ', array1)


Array of all the odd integers from 50 to 100:  [51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97
 99]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below: (or create your own array)**

    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [8]:
# method 1

import pandas as pd
import numpy as np

A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

A= np.array(A)

print(A)

np.sum(A, axis=0)


[[ 1  4  8]
 [ 5  7  3]
 [ 9 14  2]]


array([15, 25, 13])

In [9]:
# method 2


A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

array3 = np.array(A)

print('Given array: ', array3)

column_add = array3.sum(axis=0)

print('Sum of each column: ', column_add)


Given array:  [[ 1  4  8]
 [ 5  7  3]
 [ 9 14  2]]
Sum of each column:  [15 25 13]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a code to get the element-wise remainder of an array after division by 8 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
    
    num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

In [10]:
#method 1

num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

import pandas as pd
import numpy as np

array4 = np.array(num)

print('Given array: ',array4)

print('Element-wise remainder of division: ',np.remainder(array4, 8))

Given array:  [42 87 90 14 32 75 61 80 92]
Element-wise remainder of division:  [2 7 2 6 0 3 5 0 4]


In [11]:
# method 2

num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

print('Given array: ', num)

print('Element-wise remainder of division: ',np.remainder(num,8))

Given array:  [42, 87, 90, 14, 32, 75, 61, 80, 92]
Element-wise remainder of division:  [2 7 2 6 0 3 5 0 4]


<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [12]:
array_1d = np.arange(20)

array_2d = array_1d.reshape(2,10)

array_2d

array_2d[1,0:5]

array([10, 11, 12, 13, 14])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a program to find common values between two arrays 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    prices_monday = [10, 30, 50, 60, 90]

    prices_tuesday = [50, 20, 80, 125, 10, 70]

In [13]:
prices_monday = [10, 30, 50, 60, 90]

prices_tuesday = [50, 20, 80, 125, 10, 70]


array_prices_monday = np.array([10, 30, 50, 60, 90])

array_prices_tuesday = np.array([50, 20, 80, 125, 10, 70])

np.intersect1d(array_prices_monday,array_prices_tuesday)


array([10, 50])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to find BMI of the patients whose height and weight is provided in the list given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    list of weights (in kg)
    weights = [57, 69, 54, 65 ,71, 62, 56]

    list of heights (in m)<br>
    heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

In [14]:
# BMI = weight / height**2 

weights = np.array([57, 69, 54, 65 ,71, 62, 56])
heights = np.array([1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53])

BMI = weights/heights**2

BMI

np.round(BMI)

#1.6  =  2

#1.4   = 1


array([23., 23., 20., 21., 26., 21., 24.])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a program to add a new column ([5,7]) at the last position in the array given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    array1 = [[[3, 4], [8, 2],[5, 9]]]

In [15]:
array1 = [[[3, 4], [8, 2],[5, 9]]]

array1

new_array  = np.insert(array1, obj = 3 , values = [5,7] , axis=1)
new_array

array([[[3, 4],
        [8, 2],
        [5, 9],
        [5, 7]]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a code to print the identity matrix of order 5</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [16]:
identity_5 = np.eye(5)
identity_5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Write a program to transpose a matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
    M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [17]:
M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

print('Matrix: ',np.array(M))

print('Transpose: ', np.transpose(M))

Matrix:  [[15 17 45 56]
 [ 7 42 15 63]
 [54  3 61 41]
 [ 0 87 16 20]]
Transpose:  [[15  7 54  0]
 [17 42  3 87]
 [45 15 61 16]
 [56 63 41 20]]


<a id="Stacking"> </a>
## 3. Stacking

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>14. Write a program to combine the two arrays vertically</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**<br>

    A1 = [[5, 9], [7, 6]]

    A2 = [[8,-7], [0,4]]

Combine the array A2 with A1

In [18]:
import numpy as np
import pandas as pd

A1 = [[5, 9], [7, 6]]

A2 = [[8,-7], [0,4]]

A1 = np.array(A1)

A2 = np.array(A2)

updated_array = np.vstack((A2,A1))
updated_array


array([[ 8, -7],
       [ 0,  4],
       [ 5,  9],
       [ 7,  6]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>15. Write a code to combine the two arrays horizontally</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the arrays given below: (or create your own array)**

    A1 = [[-81, 75, 40], [27, 67, 52]]

    A2 = [[15, 54], [39, 56]]

Combine the array A2 with A1

In [19]:
A1 = [[-81, 75, 40], [27, 67, 52]]

A2 = [[15, 54], [39, 56]]

A1 = np.array(A1)

A2 = np.array(A2)

updated_array = np.hstack((A2,A1))
updated_array

array([[ 15,  54, -81,  75,  40],
       [ 39,  56,  27,  67,  52]])

<a id="Splitting"> </a>
## 4. Splitting

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>16. Write a code to divide the array into three sub-arrays containing
                       equal number of rows</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>

    A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]

In [20]:
A = [[4, 7], [2, -3], [8, 1], [0, 9], [5,-1], [8, 3]]

A = np.array(A)

# vertical split

A_vertical_split = np.vsplit(A,3)

A_vertical_split


[array([[ 4,  7],
        [ 2, -3]]),
 array([[8, 1],
        [0, 9]]),
 array([[ 5, -1],
        [ 8,  3]])]

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>17. Write a program to divide the array into two sub-arrays containing equal number of columns
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**

    B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

In [21]:
B = [[8, 7, 0, 9], [2, -3, 5, 10], [8, 5, -1,3]]

B = np.array(B)

B_horizontal_split = np.hsplit(B,2)
B_horizontal_split


[array([[ 8,  7],
        [ 2, -3],
        [ 8,  5]]),
 array([[ 0,  9],
        [ 5, 10],
        [-1,  3]])]

<a id="loop"> </a>
## 5. For Loop

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>18. Write a program to perform one-to-one mapping of the two lists</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below: (or create your own lists)**<br>

    L1 = [45, 67, 56, 71, 54, 62, 56]

    L2 = [21, 52, 64, 10, 49, 74, 26]

In [22]:
L1 = [45, 67, 56, 71, 54, 62, 56]

L2 = [21, 52, 64, 10, 49, 74, 26]


for x,y in zip(L1,L2):
    print(x,y)

45 21
67 52
56 64
71 10
54 49
62 74
56 26


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>19. Define a for loop to apply the function (2x-1)/(x+5) on every element of an array </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**
    
    numbers = [6, 5, 3, 15]

In [23]:
numbers = [6, 5, 3, 15]

numbers = np.array([6, 5, 3, 15])
for x in numbers:
    print((2*x-1)/(x+5))


1.0
0.9
0.625
1.45
